"""
This type stub file was generated by pyright.
"""

import pytest
from typing import Generator
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session
from kanot.db.crud import DatabaseManager
from sqlalchemy.engine import Engine

TEST_DB_URL = ...
engine = ...
TestingSessionLocal = ...
@pytest.fixture(scope="session")
def db_engine(): # -> Generator[Engine, Any, None]:
    ...

@pytest.fixture(scope="function")
def db_session(db_engine: Engine): # -> Generator[Session, Any, None]:
    ...

@pytest.fixture(scope="function")
def client(db_session: Session) -> Generator[TestClient, None, None]:
    ...

@pytest.fixture(scope="function")
def db_manager(db_session: Session) -> DatabaseManager:
    ...

